### ISSUE TITLE
Aphrodisiac Gestation issues

### ISSUE THREAD

**Issue by iMasonite** [iMasonite/KenetiCommunityMod#6]
From Discord: @lionheart

When mating using the Aphrodisiac. Sometimes the gestation is hanging  and going past 100%. EG ticking up to 105%. The Dino is not giving birth until after the aphrodisiac wears off resulting is a full normal CD.
This is while staying in render of the dino. The Two dinos ive had issues with are Megatherums and Doeds but these are just the ones im trying to breed atm.

I had used an Aphrodisiac. they all had the buff but ticked up to 104.9% / 105% gestation and gave birth after the Buff has worn off. Leaving a 4 - 8hr CD.

![Image](https://github.com/iMasonite/KenetiCommunityMod/assets/4611812/9679f4ee-3f56-4a62-afd1-2c93f3bd93ce)

![Image](https://github.com/iMasonite/KenetiCommunityMod/assets/4611812/21615f52-50da-4255-891b-2f42bbdb6d8a)

**Comment by iMasonite** [comment]
- Fixed gestating creatures gestating more than 100%
 - Adjusted buff to complete gestating 8% before buff ends instead of 5%
 - Added a check to force the buff to continue working if the gestation gets stuck at 100% or more. (because ARK...)

**Comment by calsberg01** [comment]
Tested in live. Issue still persists. Out of 12 Megatheriums mated under aphrodisiac, 3 had a longer cool down than the others. One as long as 7 hours. 




![Image](https://github.com/iMasonite/KenetiCommunityMod/assets/155387525/5eabb752-3349-4848-b4ee-1b4b6e97ef27)

**Comment by iMasonite** [comment]
This seems to be a replication issue, where the client is not receiving the correct buff timers.

I've added some additional force replication functions to see if this solves the replication issue.
